// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Use the **zpa_application_segment_pra** data source to get information about an application segment for Privileged Remote Access in the Zscaler Private Access cloud. This resource can then be referenced in an access policy rule, access policy timeout rule, access policy client forwarding rule and inspection policy. This resource supports Privileged Remote Access for both `RDP` and `SSH`.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const this = zpa.ApplicationSegment.getApplicationSegmentPRA({
 *     name: "PRA_Example",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const this = zpa.ApplicationSegment.getApplicationSegmentPRA({
 *     id: "123456789",
 * });
 * ```
 */
export function getApplicationSegmentPRA(args?: GetApplicationSegmentPRAArgs, opts?: pulumi.InvokeOptions): Promise<GetApplicationSegmentPRAResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:ApplicationSegment/getApplicationSegmentPRA:getApplicationSegmentPRA", {
        "id": args.id,
        "name": args.name,
        "tcpPortRanges": args.tcpPortRanges,
        "udpPortRanges": args.udpPortRanges,
    }, opts);
}

/**
 * A collection of arguments for invoking getApplicationSegmentPRA.
 */
export interface GetApplicationSegmentPRAArgs {
    id?: string;
    /**
     * The name of the PRA Application Segment to be exported.
     */
    name?: string;
    /**
     * (string) TCP port ranges used to access the app.
     * * `from:`
     * * `to:`
     */
    tcpPortRanges?: inputs.ApplicationSegment.GetApplicationSegmentPRATcpPortRange[];
    /**
     * (string) UDP port ranges used to access the app.
     * * `from:`
     * * `to:`
     */
    udpPortRanges?: inputs.ApplicationSegment.GetApplicationSegmentPRAUdpPortRange[];
}

/**
 * A collection of values returned by getApplicationSegmentPRA.
 */
export interface GetApplicationSegmentPRAResult {
    /**
     * (string) Indicates whether users can bypass ZPA to access applications.
     */
    readonly bypassType: string;
    /**
     * (string)
     */
    readonly configSpace: string;
    /**
     * (string) Description of the application.
     */
    readonly description: string;
    /**
     * (string) List of domains and IPs.
     */
    readonly domainNames: string[];
    /**
     * (bool) Whether Double Encryption is enabled or disabled for the app.
     */
    readonly doubleEncrypt: boolean;
    /**
     * (bool) Whether this application is enabled or not
     */
    readonly enabled: boolean;
    /**
     * (string)
     */
    readonly healthCheckType: string;
    /**
     * (string) Whether health reporting for the app is Continuous or On Access. Supported values: NONE, ON_ACCESS, CONTINUOUS.
     */
    readonly healthReporting: string;
    readonly id?: string;
    /**
     * (bool)
     */
    readonly ipAnchored: boolean;
    /**
     * (bool) Indicates if the Zscaler Client Connector (formerly Zscaler App or Z App) receives CNAME DNS records from the connectors.
     */
    readonly isCnameEnabled: boolean;
    readonly name?: string;
    /**
     * (bool)
     */
    readonly passiveHealthEnabled: boolean;
    /**
     * (String) Segment Group IDs
     */
    readonly segmentGroupId: string;
    readonly segmentGroupName: string;
    /**
     * (string) List of Server Group IDs
     * * `id:` - (string) List of Server Group IDs
     */
    readonly serverGroups: outputs.ApplicationSegment.GetApplicationSegmentPRAServerGroup[];
    /**
     * (string) TCP port ranges used to access the app.
     * * `app_id:` - (string)
     * * `name:` - (string) Name of the Privileged Remote Access
     * * `description:` - (string) Description of the Privileged Remote Access
     * * `domain:` - (string) Domain name of the Privileged Remote Access
     */
    readonly sraApps: outputs.ApplicationSegment.GetApplicationSegmentPRASraApp[];
    /**
     * (string) TCP port ranges used to access the app.
     */
    readonly tcpPortRanges: string[];
    /**
     * (string) UDP port ranges used to access the app.
     */
    readonly udpPortRanges: string[];
}
/**
 * Use the **zpa_application_segment_pra** data source to get information about an application segment for Privileged Remote Access in the Zscaler Private Access cloud. This resource can then be referenced in an access policy rule, access policy timeout rule, access policy client forwarding rule and inspection policy. This resource supports Privileged Remote Access for both `RDP` and `SSH`.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const this = zpa.ApplicationSegment.getApplicationSegmentPRA({
 *     name: "PRA_Example",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const this = zpa.ApplicationSegment.getApplicationSegmentPRA({
 *     id: "123456789",
 * });
 * ```
 */
export function getApplicationSegmentPRAOutput(args?: GetApplicationSegmentPRAOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetApplicationSegmentPRAResult> {
    return pulumi.output(args).apply((a: any) => getApplicationSegmentPRA(a, opts))
}

/**
 * A collection of arguments for invoking getApplicationSegmentPRA.
 */
export interface GetApplicationSegmentPRAOutputArgs {
    id?: pulumi.Input<string>;
    /**
     * The name of the PRA Application Segment to be exported.
     */
    name?: pulumi.Input<string>;
    /**
     * (string) TCP port ranges used to access the app.
     * * `from:`
     * * `to:`
     */
    tcpPortRanges?: pulumi.Input<pulumi.Input<inputs.ApplicationSegment.GetApplicationSegmentPRATcpPortRangeArgs>[]>;
    /**
     * (string) UDP port ranges used to access the app.
     * * `from:`
     * * `to:`
     */
    udpPortRanges?: pulumi.Input<pulumi.Input<inputs.ApplicationSegment.GetApplicationSegmentPRAUdpPortRangeArgs>[]>;
}
