// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const example = zpa.SegmentGroup.getSegmentGroup({
 *     name: "segment_group_name",
 * });
 * ```
 */
export function getSegmentGroup(args?: GetSegmentGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetSegmentGroupResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:SegmentGroup/getSegmentGroup:getSegmentGroup", {
        "id": args.id,
        "name": args.name,
        "policyMigrated": args.policyMigrated,
    }, opts);
}

/**
 * A collection of arguments for invoking getSegmentGroup.
 */
export interface GetSegmentGroupArgs {
    /**
     * The ID of the segment group to be exported.
     */
    id?: string;
    /**
     * The name of the segment group to be exported.
     */
    name?: string;
    /**
     * (bool)
     */
    policyMigrated?: boolean;
}

/**
 * A collection of values returned by getSegmentGroup.
 */
export interface GetSegmentGroupResult {
    /**
     * (Computed)
     */
    readonly applications: outputs.SegmentGroup.GetSegmentGroupApplication[];
    /**
     * (string)
     */
    readonly configSpace: string;
    /**
     * (string)
     */
    readonly creationTime: string;
    /**
     * (string)
     */
    readonly description: string;
    /**
     * (bool)
     */
    readonly enabled: boolean;
    /**
     * (string)
     */
    readonly id?: string;
    /**
     * (string)
     */
    readonly modifiedBy: string;
    /**
     * (string)
     */
    readonly modifiedTime: string;
    /**
     * (string)
     */
    readonly name?: string;
    /**
     * (bool)
     */
    readonly policyMigrated: boolean;
    /**
     * (string)
     */
    readonly tcpKeepAliveEnabled: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const example = zpa.SegmentGroup.getSegmentGroup({
 *     name: "segment_group_name",
 * });
 * ```
 */
export function getSegmentGroupOutput(args?: GetSegmentGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSegmentGroupResult> {
    return pulumi.output(args).apply((a: any) => getSegmentGroup(a, opts))
}

/**
 * A collection of arguments for invoking getSegmentGroup.
 */
export interface GetSegmentGroupOutputArgs {
    /**
     * The ID of the segment group to be exported.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the segment group to be exported.
     */
    name?: pulumi.Input<string>;
    /**
     * (bool)
     */
    policyMigrated?: pulumi.Input<boolean>;
}
