// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.Inputs
{

    public sealed class ZPAInspectionCustomControlsRuleConditionsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("lhs")]
        public Input<string>? Lhs { get; set; }

        [Input("op")]
        public Input<string>? Op { get; set; }

        [Input("rhs")]
        public Input<string>? Rhs { get; set; }

        public ZPAInspectionCustomControlsRuleConditionsGetArgs()
        {
        }
        public static new ZPAInspectionCustomControlsRuleConditionsGetArgs Empty => new ZPAInspectionCustomControlsRuleConditionsGetArgs();
    }
}
