// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.Inputs
{

    public sealed class ZPALSSConfigControllerPolicyRuleResourceConditionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Optional)
        /// * `operator` (Optional) - Supported values are: `AND` or `OR`
        /// * `operands`
        /// * `object_type` (Optional) This is for specifying the policy critiera. Supported values: `APP`, `APP_GROUP`, `CLIENT_TYPE`, `TRUSTED_NETWORK`, `SAML`, `SCIM`, `SCIM_GROUP`
        /// * `values` (Optional) The below values are supported when choosing `object_type` of type `CLIENT_TYPE`.
        /// - `zpn_client_type_exporter`
        /// - `zpn_client_type_browser_isolation`
        /// - `zpn_client_type_machine_tunnel`
        /// - `zpn_client_type_ip_anchoring`
        /// - `zpn_client_type_edge_connector`
        /// - `zpn_client_type_zapp`
        /// </summary>
        [Input("negated")]
        public Input<bool>? Negated { get; set; }

        [Input("operands")]
        private InputList<Inputs.ZPALSSConfigControllerPolicyRuleResourceConditionOperandGetArgs>? _operands;
        public InputList<Inputs.ZPALSSConfigControllerPolicyRuleResourceConditionOperandGetArgs> Operands
        {
            get => _operands ?? (_operands = new InputList<Inputs.ZPALSSConfigControllerPolicyRuleResourceConditionOperandGetArgs>());
            set => _operands = value;
        }

        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        public ZPALSSConfigControllerPolicyRuleResourceConditionGetArgs()
        {
        }
        public static new ZPALSSConfigControllerPolicyRuleResourceConditionGetArgs Empty => new ZPALSSConfigControllerPolicyRuleResourceConditionGetArgs();
    }
}
