// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.Inputs
{

    public sealed class ZPAPolicyAccessRuleConditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Optional) The ID of a server group resource
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// (Optional) Supported values: ``true`` or ``false``
        /// </summary>
        [Input("negated")]
        public Input<bool>? Negated { get; set; }

        [Input("operands")]
        private InputList<Inputs.ZPAPolicyAccessRuleConditionOperandArgs>? _operands;

        /// <summary>
        /// (Optional) - Operands block must be repeated if multiple per `object_type` conditions are to be added to the rule.
        /// </summary>
        public InputList<Inputs.ZPAPolicyAccessRuleConditionOperandArgs> Operands
        {
            get => _operands ?? (_operands = new InputList<Inputs.ZPAPolicyAccessRuleConditionOperandArgs>());
            set => _operands = value;
        }

        /// <summary>
        /// (Optional) Supported values: ``AND``, and ``OR``
        /// </summary>
        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        public ZPAPolicyAccessRuleConditionArgs()
        {
        }
        public static new ZPAPolicyAccessRuleConditionArgs Empty => new ZPAPolicyAccessRuleConditionArgs();
    }
}
