// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.Inspection.Inputs
{

    public sealed class InspectionCustomControlsRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        public Input<Inputs.InspectionCustomControlsRuleConditionsArgs>? Conditions { get; set; }

        [Input("names")]
        private InputList<string>? _names;
        public InputList<string> Names
        {
            get => _names ?? (_names = new InputList<string>());
            set => _names = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public InspectionCustomControlsRuleArgs()
        {
        }
        public static new InspectionCustomControlsRuleArgs Empty => new InspectionCustomControlsRuleArgs();
    }
}
