// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The **zpa_trusted_network** data source to get information about a trusted network created in the Zscaler Private Access Mobile Portal. This data source can then be referenced within the following resources:
//
// 1. Access Policy
// 2. Forwarding Policy
// 3. Inspection Policy
// 4. Isolation Policy
// 5. Service Edge Group.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.GetZPATrustedNetwork(ctx, &zpa.GetZPATrustedNetworkArgs{
//				Name: pulumi.StringRef("trusted_network_name"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// > **NOTE** To query trusted network that are associated with a specific Zscaler cloud, it is required to append the cloud name to the name of the trusted network as the below example:
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example1, err := zpa.GetZPATrustedNetwork(ctx, &zpa.GetZPATrustedNetworkArgs{
//				Name: pulumi.StringRef("Corporate-Network (zscalertwo.net)"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("zpaTrustedNetwork", example1.NetworkId)
//			return nil
//		})
//	}
//
// ```
func GetZPATrustedNetwork(ctx *pulumi.Context, args *GetZPATrustedNetworkArgs, opts ...pulumi.InvokeOption) (*GetZPATrustedNetworkResult, error) {
	var rv GetZPATrustedNetworkResult
	err := ctx.Invoke("zpa:index/getZPATrustedNetwork:getZPATrustedNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPATrustedNetwork.
type GetZPATrustedNetworkArgs struct {
	// The ID of the posture profile to be exported.
	Id *string `pulumi:"id"`
	// The name of the posture profile to be exported.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZPATrustedNetwork.
type GetZPATrustedNetworkResult struct {
	// (string)
	CreationTime string `pulumi:"creationTime"`
	// (string)
	Domain string  `pulumi:"domain"`
	Id     *string `pulumi:"id"`
	// (string)
	ModifiedTime string  `pulumi:"modifiedTime"`
	Modifiedby   string  `pulumi:"modifiedby"`
	Name         *string `pulumi:"name"`
	// (string)
	NetworkId string `pulumi:"networkId"`
	// (string)
	ZscalerCloud string `pulumi:"zscalerCloud"`
}

func GetZPATrustedNetworkOutput(ctx *pulumi.Context, args GetZPATrustedNetworkOutputArgs, opts ...pulumi.InvokeOption) GetZPATrustedNetworkResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZPATrustedNetworkResult, error) {
			args := v.(GetZPATrustedNetworkArgs)
			r, err := GetZPATrustedNetwork(ctx, &args, opts...)
			var s GetZPATrustedNetworkResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZPATrustedNetworkResultOutput)
}

// A collection of arguments for invoking getZPATrustedNetwork.
type GetZPATrustedNetworkOutputArgs struct {
	// The ID of the posture profile to be exported.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the posture profile to be exported.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZPATrustedNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPATrustedNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getZPATrustedNetwork.
type GetZPATrustedNetworkResultOutput struct{ *pulumi.OutputState }

func (GetZPATrustedNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPATrustedNetworkResult)(nil)).Elem()
}

func (o GetZPATrustedNetworkResultOutput) ToGetZPATrustedNetworkResultOutput() GetZPATrustedNetworkResultOutput {
	return o
}

func (o GetZPATrustedNetworkResultOutput) ToGetZPATrustedNetworkResultOutputWithContext(ctx context.Context) GetZPATrustedNetworkResultOutput {
	return o
}

// (string)
func (o GetZPATrustedNetworkResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

// (string)
func (o GetZPATrustedNetworkResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o GetZPATrustedNetworkResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// (string)
func (o GetZPATrustedNetworkResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o GetZPATrustedNetworkResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o GetZPATrustedNetworkResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// (string)
func (o GetZPATrustedNetworkResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

// (string)
func (o GetZPATrustedNetworkResultOutput) ZscalerCloud() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPATrustedNetworkResult) string { return v.ZscalerCloud }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZPATrustedNetworkResultOutput{})
}
