// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.LookupZPAProvisioningKey(ctx, &zpa.LookupZPAProvisioningKeyArgs{
//				AssociationType: "CONNECTOR_GRP",
//				Name:            pulumi.StringRef("Provisioning_Key"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.LookupZPAProvisioningKey(ctx, &zpa.LookupZPAProvisioningKeyArgs{
//				AssociationType: "SERVICE_EDGE_GRP",
//				Name:            pulumi.StringRef("Provisioning_Key"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupZPAProvisioningKey(ctx *pulumi.Context, args *LookupZPAProvisioningKeyArgs, opts ...pulumi.InvokeOption) (*LookupZPAProvisioningKeyResult, error) {
	var rv LookupZPAProvisioningKeyResult
	err := ctx.Invoke("zpa:index/getZPAProvisioningKey:getZPAProvisioningKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPAProvisioningKey.
type LookupZPAProvisioningKeyArgs struct {
	// Specifies the provisioning key type for App Connectors or ZPA Private Service Edges. The supported values are `CONNECTOR_GRP` and `SERVICE_EDGE_GRP`
	AssociationType string `pulumi:"associationType"`
	// The ID of the provisioning key to be exported.
	Id *string `pulumi:"id"`
	// Name of the provisioning key.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZPAProvisioningKey.
type LookupZPAProvisioningKeyResult struct {
	AppConnectorGroupId   string `pulumi:"appConnectorGroupId"`
	AppConnectorGroupName string `pulumi:"appConnectorGroupName"`
	AssociationType       string `pulumi:"associationType"`
	// (string)
	CreationTime string `pulumi:"creationTime"`
	// (bool)
	Enabled bool `pulumi:"enabled"`
	// (string)
	EnrollmentCertId string `pulumi:"enrollmentCertId"`
	// (string) Applicable only for GET calls, ignored in PUT/POST calls.
	EnrollmentCertName string `pulumi:"enrollmentCertName"`
	// (string)
	ExpirationInEpochSec string  `pulumi:"expirationInEpochSec"`
	Id                   *string `pulumi:"id"`
	// (string)
	IpAcls []string `pulumi:"ipAcls"`
	// (string)
	MaxUsage string `pulumi:"maxUsage"`
	// (string)
	ModifiedTime string  `pulumi:"modifiedTime"`
	Modifiedby   string  `pulumi:"modifiedby"`
	Name         *string `pulumi:"name"`
	// (string) Ignored in PUT/POST calls.
	ProvisioningKey string `pulumi:"provisioningKey"`
	// (string)
	UiConfig string `pulumi:"uiConfig"`
	// (string)
	UsageCount string `pulumi:"usageCount"`
	// (string)
	ZcomponentId string `pulumi:"zcomponentId"`
	// (string) Applicable only for GET calls, ignored in PUT/POST calls.
	ZcomponentName string `pulumi:"zcomponentName"`
}

func LookupZPAProvisioningKeyOutput(ctx *pulumi.Context, args LookupZPAProvisioningKeyOutputArgs, opts ...pulumi.InvokeOption) LookupZPAProvisioningKeyResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupZPAProvisioningKeyResult, error) {
			args := v.(LookupZPAProvisioningKeyArgs)
			r, err := LookupZPAProvisioningKey(ctx, &args, opts...)
			var s LookupZPAProvisioningKeyResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupZPAProvisioningKeyResultOutput)
}

// A collection of arguments for invoking getZPAProvisioningKey.
type LookupZPAProvisioningKeyOutputArgs struct {
	// Specifies the provisioning key type for App Connectors or ZPA Private Service Edges. The supported values are `CONNECTOR_GRP` and `SERVICE_EDGE_GRP`
	AssociationType pulumi.StringInput `pulumi:"associationType"`
	// The ID of the provisioning key to be exported.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Name of the provisioning key.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupZPAProvisioningKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZPAProvisioningKeyArgs)(nil)).Elem()
}

// A collection of values returned by getZPAProvisioningKey.
type LookupZPAProvisioningKeyResultOutput struct{ *pulumi.OutputState }

func (LookupZPAProvisioningKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZPAProvisioningKeyResult)(nil)).Elem()
}

func (o LookupZPAProvisioningKeyResultOutput) ToLookupZPAProvisioningKeyResultOutput() LookupZPAProvisioningKeyResultOutput {
	return o
}

func (o LookupZPAProvisioningKeyResultOutput) ToLookupZPAProvisioningKeyResultOutputWithContext(ctx context.Context) LookupZPAProvisioningKeyResultOutput {
	return o
}

func (o LookupZPAProvisioningKeyResultOutput) AppConnectorGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.AppConnectorGroupId }).(pulumi.StringOutput)
}

func (o LookupZPAProvisioningKeyResultOutput) AppConnectorGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.AppConnectorGroupName }).(pulumi.StringOutput)
}

func (o LookupZPAProvisioningKeyResultOutput) AssociationType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.AssociationType }).(pulumi.StringOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

// (bool)
func (o LookupZPAProvisioningKeyResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) EnrollmentCertId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.EnrollmentCertId }).(pulumi.StringOutput)
}

// (string) Applicable only for GET calls, ignored in PUT/POST calls.
func (o LookupZPAProvisioningKeyResultOutput) EnrollmentCertName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.EnrollmentCertName }).(pulumi.StringOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) ExpirationInEpochSec() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.ExpirationInEpochSec }).(pulumi.StringOutput)
}

func (o LookupZPAProvisioningKeyResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) IpAcls() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) []string { return v.IpAcls }).(pulumi.StringArrayOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) MaxUsage() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.MaxUsage }).(pulumi.StringOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o LookupZPAProvisioningKeyResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o LookupZPAProvisioningKeyResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// (string) Ignored in PUT/POST calls.
func (o LookupZPAProvisioningKeyResultOutput) ProvisioningKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.ProvisioningKey }).(pulumi.StringOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) UiConfig() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.UiConfig }).(pulumi.StringOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) UsageCount() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.UsageCount }).(pulumi.StringOutput)
}

// (string)
func (o LookupZPAProvisioningKeyResultOutput) ZcomponentId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.ZcomponentId }).(pulumi.StringOutput)
}

// (string) Applicable only for GET calls, ignored in PUT/POST calls.
func (o LookupZPAProvisioningKeyResultOutput) ZcomponentName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAProvisioningKeyResult) string { return v.ZcomponentName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupZPAProvisioningKeyResultOutput{})
}
