// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.LookupZPAAppConnectorGroup(ctx, &zpa.LookupZPAAppConnectorGroupArgs{
//				Name: pulumi.StringRef("DataCenter"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.LookupZPAAppConnectorGroup(ctx, &zpa.LookupZPAAppConnectorGroupArgs{
//				Id: pulumi.StringRef("123456789"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupZPAAppConnectorGroup(ctx *pulumi.Context, args *LookupZPAAppConnectorGroupArgs, opts ...pulumi.InvokeOption) (*LookupZPAAppConnectorGroupResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupZPAAppConnectorGroupResult
	err := ctx.Invoke("zpa:index/getZPAAppConnectorGroup:getZPAAppConnectorGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPAAppConnectorGroup.
type LookupZPAAppConnectorGroupArgs struct {
	// ID of the App Connector Group.
	Id *string `pulumi:"id"`
	// Name of the App Connector Group.
	Name *string `pulumi:"name"`
	// (bool) Whether the default version profile of the App Connector Group is applied or overridden. Default: `false` Supported values: `true`, `false`
	OverrideVersionProfile *bool `pulumi:"overrideVersionProfile"`
}

// A collection of values returned by getZPAAppConnectorGroup.
type LookupZPAAppConnectorGroupResult struct {
	// (String) Whether Double Encryption is enabled or disabled for the app.
	CityCountry string                             `pulumi:"cityCountry"`
	Connectors  []GetZPAAppConnectorGroupConnector `pulumi:"connectors"`
	// (String)
	CountryCode  string `pulumi:"countryCode"`
	CreationTime string `pulumi:"creationTime"`
	Description  string `pulumi:"description"`
	// (String)
	// * ``0`` = ``Default``
	// * ``1`` = ``Previous Default``
	// * ``2`` = ``New Release``
	DnsQueryType string `pulumi:"dnsQueryType"`
	// (String) Whether this App Connector Group is enabled or not. Default value: `true`. Supported values: `true`, `false`
	Enabled bool `pulumi:"enabled"`
	// (String)
	GeoLocationId string  `pulumi:"geoLocationId"`
	Id            *string `pulumi:"id"`
	// (String) Latitude of the App Connector Group. Integer or decimal. With values in the range of `-90` to `90`
	Latitude string `pulumi:"latitude"`
	// (String) Location of the App Connector Group.
	Location string `pulumi:"location"`
	// (String) Longitude of the App Connector Group. Integer or decimal. With values in the range of `-180` to `180`
	Longitude            string  `pulumi:"longitude"`
	LssAppConnectorGroup bool    `pulumi:"lssAppConnectorGroup"`
	ModifiedTime         string  `pulumi:"modifiedTime"`
	Modifiedby           string  `pulumi:"modifiedby"`
	Name                 *string `pulumi:"name"`
	// (bool) Whether the default version profile of the App Connector Group is applied or overridden. Default: `false` Supported values: `true`, `false`
	OverrideVersionProfile   *bool                                `pulumi:"overrideVersionProfile"`
	ServerGroups             []GetZPAAppConnectorGroupServerGroup `pulumi:"serverGroups"`
	TcpQuickAckApp           bool                                 `pulumi:"tcpQuickAckApp"`
	TcpQuickAckAssistant     bool                                 `pulumi:"tcpQuickAckAssistant"`
	TcpQuickAckReadAssistant bool                                 `pulumi:"tcpQuickAckReadAssistant"`
	// (String) App Connectors in this group will attempt to update to a newer version of the software during this specified day
	UpgradeDay string `pulumi:"upgradeDay"`
	// (String) App Connectors in this group will attempt to update to a newer version of the software during this specified time. Default value: `66600`. Integer in seconds (i.e., `-66600`). The integer should be greater than or equal to `0` and less than `86400`, in `15` minute intervals
	UpgradeTimeInSecs string `pulumi:"upgradeTimeInSecs"`
	UseInDrMode       bool   `pulumi:"useInDrMode"`
	// (String) ID of the version profile.
	// Exported values are:
	// * ``0`` = ``Default``
	// * ``1`` = ``Previous Default``
	// * ``2`` = ``New Release``
	VersionProfileId string `pulumi:"versionProfileId"`
	// (String)
	// Exported values are:
	// * ``Default`` = ``0``
	// * ``Previous Default`` = ``1``
	// * ``New Release`` = ``2``
	VersionProfileName string `pulumi:"versionProfileName"`
	// (String)
	// Exported values are:
	// * ``"IPV4_IPV6"``
	// * ``"IPV4"``
	// * ``"IPV6``
	VersionProfileVisibilityScope string `pulumi:"versionProfileVisibilityScope"`
}

func LookupZPAAppConnectorGroupOutput(ctx *pulumi.Context, args LookupZPAAppConnectorGroupOutputArgs, opts ...pulumi.InvokeOption) LookupZPAAppConnectorGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupZPAAppConnectorGroupResult, error) {
			args := v.(LookupZPAAppConnectorGroupArgs)
			r, err := LookupZPAAppConnectorGroup(ctx, &args, opts...)
			var s LookupZPAAppConnectorGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupZPAAppConnectorGroupResultOutput)
}

// A collection of arguments for invoking getZPAAppConnectorGroup.
type LookupZPAAppConnectorGroupOutputArgs struct {
	// ID of the App Connector Group.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Name of the App Connector Group.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// (bool) Whether the default version profile of the App Connector Group is applied or overridden. Default: `false` Supported values: `true`, `false`
	OverrideVersionProfile pulumi.BoolPtrInput `pulumi:"overrideVersionProfile"`
}

func (LookupZPAAppConnectorGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZPAAppConnectorGroupArgs)(nil)).Elem()
}

// A collection of values returned by getZPAAppConnectorGroup.
type LookupZPAAppConnectorGroupResultOutput struct{ *pulumi.OutputState }

func (LookupZPAAppConnectorGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZPAAppConnectorGroupResult)(nil)).Elem()
}

func (o LookupZPAAppConnectorGroupResultOutput) ToLookupZPAAppConnectorGroupResultOutput() LookupZPAAppConnectorGroupResultOutput {
	return o
}

func (o LookupZPAAppConnectorGroupResultOutput) ToLookupZPAAppConnectorGroupResultOutputWithContext(ctx context.Context) LookupZPAAppConnectorGroupResultOutput {
	return o
}

// (String) Whether Double Encryption is enabled or disabled for the app.
func (o LookupZPAAppConnectorGroupResultOutput) CityCountry() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.CityCountry }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) Connectors() GetZPAAppConnectorGroupConnectorArrayOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) []GetZPAAppConnectorGroupConnector { return v.Connectors }).(GetZPAAppConnectorGroupConnectorArrayOutput)
}

// (String)
func (o LookupZPAAppConnectorGroupResultOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.CountryCode }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.Description }).(pulumi.StringOutput)
}

// (String)
// * “0“ = “Default“
// * “1“ = “Previous Default“
// * “2“ = “New Release“
func (o LookupZPAAppConnectorGroupResultOutput) DnsQueryType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.DnsQueryType }).(pulumi.StringOutput)
}

// (String) Whether this App Connector Group is enabled or not. Default value: `true`. Supported values: `true`, `false`
func (o LookupZPAAppConnectorGroupResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// (String)
func (o LookupZPAAppConnectorGroupResultOutput) GeoLocationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.GeoLocationId }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// (String) Latitude of the App Connector Group. Integer or decimal. With values in the range of `-90` to `90`
func (o LookupZPAAppConnectorGroupResultOutput) Latitude() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.Latitude }).(pulumi.StringOutput)
}

// (String) Location of the App Connector Group.
func (o LookupZPAAppConnectorGroupResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.Location }).(pulumi.StringOutput)
}

// (String) Longitude of the App Connector Group. Integer or decimal. With values in the range of `-180` to `180`
func (o LookupZPAAppConnectorGroupResultOutput) Longitude() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.Longitude }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) LssAppConnectorGroup() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) bool { return v.LssAppConnectorGroup }).(pulumi.BoolOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// (bool) Whether the default version profile of the App Connector Group is applied or overridden. Default: `false` Supported values: `true`, `false`
func (o LookupZPAAppConnectorGroupResultOutput) OverrideVersionProfile() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) *bool { return v.OverrideVersionProfile }).(pulumi.BoolPtrOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) ServerGroups() GetZPAAppConnectorGroupServerGroupArrayOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) []GetZPAAppConnectorGroupServerGroup { return v.ServerGroups }).(GetZPAAppConnectorGroupServerGroupArrayOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) TcpQuickAckApp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) bool { return v.TcpQuickAckApp }).(pulumi.BoolOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) TcpQuickAckAssistant() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) bool { return v.TcpQuickAckAssistant }).(pulumi.BoolOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) TcpQuickAckReadAssistant() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) bool { return v.TcpQuickAckReadAssistant }).(pulumi.BoolOutput)
}

// (String) App Connectors in this group will attempt to update to a newer version of the software during this specified day
func (o LookupZPAAppConnectorGroupResultOutput) UpgradeDay() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.UpgradeDay }).(pulumi.StringOutput)
}

// (String) App Connectors in this group will attempt to update to a newer version of the software during this specified time. Default value: `66600`. Integer in seconds (i.e., `-66600`). The integer should be greater than or equal to `0` and less than `86400`, in `15` minute intervals
func (o LookupZPAAppConnectorGroupResultOutput) UpgradeTimeInSecs() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.UpgradeTimeInSecs }).(pulumi.StringOutput)
}

func (o LookupZPAAppConnectorGroupResultOutput) UseInDrMode() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) bool { return v.UseInDrMode }).(pulumi.BoolOutput)
}

// (String) ID of the version profile.
// Exported values are:
// * “0“ = “Default“
// * “1“ = “Previous Default“
// * “2“ = “New Release“
func (o LookupZPAAppConnectorGroupResultOutput) VersionProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.VersionProfileId }).(pulumi.StringOutput)
}

// (String)
// Exported values are:
// * “Default“ = “0“
// * “Previous Default“ = “1“
// * “New Release“ = “2“
func (o LookupZPAAppConnectorGroupResultOutput) VersionProfileName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.VersionProfileName }).(pulumi.StringOutput)
}

// (String)
// Exported values are:
// * “"IPV4_IPV6"“
// * “"IPV4"“
// * “"IPV6“
func (o LookupZPAAppConnectorGroupResultOutput) VersionProfileVisibilityScope() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAAppConnectorGroupResult) string { return v.VersionProfileVisibilityScope }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupZPAAppConnectorGroupResultOutput{})
}
