// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.LookupZPAApplicationSegment(ctx, &zpa.LookupZPAApplicationSegmentArgs{
//				Name: pulumi.StringRef("example"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.LookupZPAApplicationSegment(ctx, &zpa.LookupZPAApplicationSegmentArgs{
//				Id: pulumi.StringRef("123456789"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupZPAApplicationSegment(ctx *pulumi.Context, args *LookupZPAApplicationSegmentArgs, opts ...pulumi.InvokeOption) (*LookupZPAApplicationSegmentResult, error) {
	var rv LookupZPAApplicationSegmentResult
	err := ctx.Invoke("zpa:index/getZPAApplicationSegment:getZPAApplicationSegment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPAApplicationSegment.
type LookupZPAApplicationSegmentArgs struct {
	Id *string `pulumi:"id"`
	// Name of the application.
	Name          *string                                `pulumi:"name"`
	TcpPortRanges []GetZPAApplicationSegmentTcpPortRange `pulumi:"tcpPortRanges"`
	UdpPortRanges []GetZPAApplicationSegmentUdpPortRange `pulumi:"udpPortRanges"`
}

// A collection of values returned by getZPAApplicationSegment.
type LookupZPAApplicationSegmentResult struct {
	BypassType                string                                `pulumi:"bypassType"`
	ConfigSpace               string                                `pulumi:"configSpace"`
	CreationTime              string                                `pulumi:"creationTime"`
	DefaultIdleTimeout        string                                `pulumi:"defaultIdleTimeout"`
	DefaultMaxAge             string                                `pulumi:"defaultMaxAge"`
	Description               string                                `pulumi:"description"`
	DomainNames               []string                              `pulumi:"domainNames"`
	DoubleEncrypt             bool                                  `pulumi:"doubleEncrypt"`
	Enabled                   bool                                  `pulumi:"enabled"`
	HealthCheckType           string                                `pulumi:"healthCheckType"`
	HealthReporting           string                                `pulumi:"healthReporting"`
	Id                        *string                               `pulumi:"id"`
	IpAnchored                bool                                  `pulumi:"ipAnchored"`
	IsCnameEnabled            bool                                  `pulumi:"isCnameEnabled"`
	ModifiedTime              string                                `pulumi:"modifiedTime"`
	Modifiedby                string                                `pulumi:"modifiedby"`
	Name                      *string                               `pulumi:"name"`
	PassiveHealthEnabled      bool                                  `pulumi:"passiveHealthEnabled"`
	SegmentGroupId            string                                `pulumi:"segmentGroupId"`
	SegmentGroupName          string                                `pulumi:"segmentGroupName"`
	SelectConnectorCloseToApp bool                                  `pulumi:"selectConnectorCloseToApp"`
	ServerGroups              []GetZPAApplicationSegmentServerGroup `pulumi:"serverGroups"`
	TcpPortRanges             []string                              `pulumi:"tcpPortRanges"`
	UdpPortRanges             []string                              `pulumi:"udpPortRanges"`
}

func LookupZPAApplicationSegmentOutput(ctx *pulumi.Context, args LookupZPAApplicationSegmentOutputArgs, opts ...pulumi.InvokeOption) LookupZPAApplicationSegmentResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupZPAApplicationSegmentResult, error) {
			args := v.(LookupZPAApplicationSegmentArgs)
			r, err := LookupZPAApplicationSegment(ctx, &args, opts...)
			var s LookupZPAApplicationSegmentResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupZPAApplicationSegmentResultOutput)
}

// A collection of arguments for invoking getZPAApplicationSegment.
type LookupZPAApplicationSegmentOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Name of the application.
	Name          pulumi.StringPtrInput                          `pulumi:"name"`
	TcpPortRanges GetZPAApplicationSegmentTcpPortRangeArrayInput `pulumi:"tcpPortRanges"`
	UdpPortRanges GetZPAApplicationSegmentUdpPortRangeArrayInput `pulumi:"udpPortRanges"`
}

func (LookupZPAApplicationSegmentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZPAApplicationSegmentArgs)(nil)).Elem()
}

// A collection of values returned by getZPAApplicationSegment.
type LookupZPAApplicationSegmentResultOutput struct{ *pulumi.OutputState }

func (LookupZPAApplicationSegmentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZPAApplicationSegmentResult)(nil)).Elem()
}

func (o LookupZPAApplicationSegmentResultOutput) ToLookupZPAApplicationSegmentResultOutput() LookupZPAApplicationSegmentResultOutput {
	return o
}

func (o LookupZPAApplicationSegmentResultOutput) ToLookupZPAApplicationSegmentResultOutputWithContext(ctx context.Context) LookupZPAApplicationSegmentResultOutput {
	return o
}

func (o LookupZPAApplicationSegmentResultOutput) BypassType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.BypassType }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) ConfigSpace() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.ConfigSpace }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) DefaultIdleTimeout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.DefaultIdleTimeout }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) DefaultMaxAge() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.DefaultMaxAge }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) DomainNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) []string { return v.DomainNames }).(pulumi.StringArrayOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) DoubleEncrypt() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) bool { return v.DoubleEncrypt }).(pulumi.BoolOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) HealthCheckType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.HealthCheckType }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) HealthReporting() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.HealthReporting }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) IpAnchored() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) bool { return v.IpAnchored }).(pulumi.BoolOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) IsCnameEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) bool { return v.IsCnameEnabled }).(pulumi.BoolOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) PassiveHealthEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) bool { return v.PassiveHealthEnabled }).(pulumi.BoolOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) SegmentGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.SegmentGroupId }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) SegmentGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) string { return v.SegmentGroupName }).(pulumi.StringOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) SelectConnectorCloseToApp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) bool { return v.SelectConnectorCloseToApp }).(pulumi.BoolOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) ServerGroups() GetZPAApplicationSegmentServerGroupArrayOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) []GetZPAApplicationSegmentServerGroup { return v.ServerGroups }).(GetZPAApplicationSegmentServerGroupArrayOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) TcpPortRanges() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) []string { return v.TcpPortRanges }).(pulumi.StringArrayOutput)
}

func (o LookupZPAApplicationSegmentResultOutput) UdpPortRanges() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupZPAApplicationSegmentResult) []string { return v.UdpPortRanges }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupZPAApplicationSegmentResultOutput{})
}
