// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use the **zpa_ba_certificate** data source to get information about a browser access certificate created in the Zscaler Private Access cloud. This data source is required when creating a browser access application segment resource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.GetZPABaCertificate(ctx, &zpa.GetZPABaCertificateArgs{
//				Name: pulumi.StringRef("example.acme.com"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.GetZPABaCertificate(ctx, &zpa.GetZPABaCertificateArgs{
//				Id: pulumi.StringRef("1234567890"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetZPABaCertificate(ctx *pulumi.Context, args *GetZPABaCertificateArgs, opts ...pulumi.InvokeOption) (*GetZPABaCertificateResult, error) {
	var rv GetZPABaCertificateResult
	err := ctx.Invoke("zpa:index/getZPABaCertificate:getZPABaCertificate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPABaCertificate.
type GetZPABaCertificateArgs struct {
	// The id of the browser access certificate to be exported.
	Id *string `pulumi:"id"`
	// The name of the browser access certificate to be exported.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZPABaCertificate.
type GetZPABaCertificateResult struct {
	// (string)
	CertChain string `pulumi:"certChain"`
	// (string)
	Cname string `pulumi:"cname"`
	// (string)
	CreationTime string `pulumi:"creationTime"`
	// (string)
	Description string  `pulumi:"description"`
	Id          *string `pulumi:"id"`
	// (string)
	IssuedBy string `pulumi:"issuedBy"`
	// (string)
	IssuedTo string `pulumi:"issuedTo"`
	// (string)
	ModifiedTime string `pulumi:"modifiedTime"`
	// (string)
	Modifiedby string  `pulumi:"modifiedby"`
	Name       *string `pulumi:"name"`
	// (string)
	Sans []string `pulumi:"sans"`
	// (string)
	SerialNo string `pulumi:"serialNo"`
	// (string)
	Status string `pulumi:"status"`
	// (string)
	ValidFromInEpochsec string `pulumi:"validFromInEpochsec"`
	// (string)
	ValidToInEpochsec string `pulumi:"validToInEpochsec"`
}

func GetZPABaCertificateOutput(ctx *pulumi.Context, args GetZPABaCertificateOutputArgs, opts ...pulumi.InvokeOption) GetZPABaCertificateResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZPABaCertificateResult, error) {
			args := v.(GetZPABaCertificateArgs)
			r, err := GetZPABaCertificate(ctx, &args, opts...)
			var s GetZPABaCertificateResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZPABaCertificateResultOutput)
}

// A collection of arguments for invoking getZPABaCertificate.
type GetZPABaCertificateOutputArgs struct {
	// The id of the browser access certificate to be exported.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the browser access certificate to be exported.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZPABaCertificateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPABaCertificateArgs)(nil)).Elem()
}

// A collection of values returned by getZPABaCertificate.
type GetZPABaCertificateResultOutput struct{ *pulumi.OutputState }

func (GetZPABaCertificateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPABaCertificateResult)(nil)).Elem()
}

func (o GetZPABaCertificateResultOutput) ToGetZPABaCertificateResultOutput() GetZPABaCertificateResultOutput {
	return o
}

func (o GetZPABaCertificateResultOutput) ToGetZPABaCertificateResultOutputWithContext(ctx context.Context) GetZPABaCertificateResultOutput {
	return o
}

// (string)
func (o GetZPABaCertificateResultOutput) CertChain() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.CertChain }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) Cname() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.Cname }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetZPABaCertificateResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) IssuedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.IssuedBy }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) IssuedTo() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.IssuedTo }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o GetZPABaCertificateResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) Sans() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) []string { return v.Sans }).(pulumi.StringArrayOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) SerialNo() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.SerialNo }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.Status }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) ValidFromInEpochsec() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.ValidFromInEpochsec }).(pulumi.StringOutput)
}

// (string)
func (o GetZPABaCertificateResultOutput) ValidToInEpochsec() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPABaCertificateResult) string { return v.ValidToInEpochsec }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZPABaCertificateResultOutput{})
}
