// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use the **zpa_scim_attribute_header** data source to get information about a SCIM attribute from an Identity Provider (IdP). This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Inspection Policy.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.GetZPASCIMAttributeHeader(ctx, &zpa.GetZPASCIMAttributeHeaderArgs{
//				IdpName: pulumi.StringRef("IdP_Name"),
//				Name:    pulumi.StringRef("name.givenName"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = zpa.GetZPASCIMAttributeHeader(ctx, &zpa.GetZPASCIMAttributeHeaderArgs{
//				IdpName: pulumi.StringRef("IdP_Name"),
//				Name:    pulumi.StringRef("name.familyName"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetZPASCIMAttributeHeader(ctx *pulumi.Context, args *GetZPASCIMAttributeHeaderArgs, opts ...pulumi.InvokeOption) (*GetZPASCIMAttributeHeaderResult, error) {
	var rv GetZPASCIMAttributeHeaderResult
	err := ctx.Invoke("zpa:index/getZPASCIMAttributeHeader:getZPASCIMAttributeHeader", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderArgs struct {
	// (string) The ID of the IdP corresponding to the SAML attribute.
	IdpId *string `pulumi:"idpId"`
	// The name of the scim attribute header that must be exported.
	IdpName *string `pulumi:"idpName"`
	// The name of the scim attribute header to be exported.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderResult struct {
	// (string)
	CanonicalValues []string `pulumi:"canonicalValues"`
	// (bool)
	CaseSensitive bool `pulumi:"caseSensitive"`
	// (string)
	CreationTime string `pulumi:"creationTime"`
	// (string)
	DataType string `pulumi:"dataType"`
	// (string)
	Description string `pulumi:"description"`
	// (string)
	Id string `pulumi:"id"`
	// (string) The ID of the IdP corresponding to the SAML attribute.
	IdpId   *string `pulumi:"idpId"`
	IdpName *string `pulumi:"idpName"`
	// (string)
	ModifiedTime string `pulumi:"modifiedTime"`
	Modifiedby   string `pulumi:"modifiedby"`
	// (bool)
	Multivalued bool `pulumi:"multivalued"`
	// (string)
	Mutability string  `pulumi:"mutability"`
	Name       *string `pulumi:"name"`
	// (bool)
	Required bool `pulumi:"required"`
	// (string)
	Returned string `pulumi:"returned"`
	// (string)
	SchemaUri string `pulumi:"schemaUri"`
	// (bool)
	Uniqueness bool     `pulumi:"uniqueness"`
	Values     []string `pulumi:"values"`
}

func GetZPASCIMAttributeHeaderOutput(ctx *pulumi.Context, args GetZPASCIMAttributeHeaderOutputArgs, opts ...pulumi.InvokeOption) GetZPASCIMAttributeHeaderResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZPASCIMAttributeHeaderResult, error) {
			args := v.(GetZPASCIMAttributeHeaderArgs)
			r, err := GetZPASCIMAttributeHeader(ctx, &args, opts...)
			var s GetZPASCIMAttributeHeaderResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZPASCIMAttributeHeaderResultOutput)
}

// A collection of arguments for invoking getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderOutputArgs struct {
	// (string) The ID of the IdP corresponding to the SAML attribute.
	IdpId pulumi.StringPtrInput `pulumi:"idpId"`
	// The name of the scim attribute header that must be exported.
	IdpName pulumi.StringPtrInput `pulumi:"idpName"`
	// The name of the scim attribute header to be exported.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZPASCIMAttributeHeaderOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPASCIMAttributeHeaderArgs)(nil)).Elem()
}

// A collection of values returned by getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderResultOutput struct{ *pulumi.OutputState }

func (GetZPASCIMAttributeHeaderResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPASCIMAttributeHeaderResult)(nil)).Elem()
}

func (o GetZPASCIMAttributeHeaderResultOutput) ToGetZPASCIMAttributeHeaderResultOutput() GetZPASCIMAttributeHeaderResultOutput {
	return o
}

func (o GetZPASCIMAttributeHeaderResultOutput) ToGetZPASCIMAttributeHeaderResultOutputWithContext(ctx context.Context) GetZPASCIMAttributeHeaderResultOutput {
	return o
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) CanonicalValues() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) []string { return v.CanonicalValues }).(pulumi.StringArrayOutput)
}

// (bool)
func (o GetZPASCIMAttributeHeaderResultOutput) CaseSensitive() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.CaseSensitive }).(pulumi.BoolOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) DataType() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.DataType }).(pulumi.StringOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Description }).(pulumi.StringOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Id }).(pulumi.StringOutput)
}

// (string) The ID of the IdP corresponding to the SAML attribute.
func (o GetZPASCIMAttributeHeaderResultOutput) IdpId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) *string { return v.IdpId }).(pulumi.StringPtrOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) IdpName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) *string { return v.IdpName }).(pulumi.StringPtrOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

// (bool)
func (o GetZPASCIMAttributeHeaderResultOutput) Multivalued() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.Multivalued }).(pulumi.BoolOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) Mutability() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Mutability }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// (bool)
func (o GetZPASCIMAttributeHeaderResultOutput) Required() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.Required }).(pulumi.BoolOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) Returned() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Returned }).(pulumi.StringOutput)
}

// (string)
func (o GetZPASCIMAttributeHeaderResultOutput) SchemaUri() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.SchemaUri }).(pulumi.StringOutput)
}

// (bool)
func (o GetZPASCIMAttributeHeaderResultOutput) Uniqueness() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.Uniqueness }).(pulumi.BoolOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) []string { return v.Values }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZPASCIMAttributeHeaderResultOutput{})
}
