# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetIdPControllerAdminMetadataResult',
    'GetIdPControllerUserMetadataResult',
]

@pulumi.output_type
class GetIdPControllerAdminMetadataResult(dict):
    def __init__(__self__, *,
                 certificate_url: str,
                 sp_base_url: str,
                 sp_entity_id: str,
                 sp_metadata_url: str,
                 sp_post_url: str):
        """
        :param str certificate_url: (string)
        :param str sp_entity_id: (string)
        :param str sp_metadata_url: (string)
        :param str sp_post_url: (string)
        """
        pulumi.set(__self__, "certificate_url", certificate_url)
        pulumi.set(__self__, "sp_base_url", sp_base_url)
        pulumi.set(__self__, "sp_entity_id", sp_entity_id)
        pulumi.set(__self__, "sp_metadata_url", sp_metadata_url)
        pulumi.set(__self__, "sp_post_url", sp_post_url)

    @property
    @pulumi.getter(name="certificateUrl")
    def certificate_url(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "certificate_url")

    @property
    @pulumi.getter(name="spBaseUrl")
    def sp_base_url(self) -> str:
        return pulumi.get(self, "sp_base_url")

    @property
    @pulumi.getter(name="spEntityId")
    def sp_entity_id(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "sp_entity_id")

    @property
    @pulumi.getter(name="spMetadataUrl")
    def sp_metadata_url(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "sp_metadata_url")

    @property
    @pulumi.getter(name="spPostUrl")
    def sp_post_url(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "sp_post_url")


@pulumi.output_type
class GetIdPControllerUserMetadataResult(dict):
    def __init__(__self__, *,
                 certificate_url: str,
                 sp_base_url: str,
                 sp_entity_id: str,
                 sp_metadata_url: str,
                 sp_post_url: str):
        """
        :param str certificate_url: (string)
        :param str sp_entity_id: (string)
        :param str sp_metadata_url: (string)
        :param str sp_post_url: (string)
        """
        pulumi.set(__self__, "certificate_url", certificate_url)
        pulumi.set(__self__, "sp_base_url", sp_base_url)
        pulumi.set(__self__, "sp_entity_id", sp_entity_id)
        pulumi.set(__self__, "sp_metadata_url", sp_metadata_url)
        pulumi.set(__self__, "sp_post_url", sp_post_url)

    @property
    @pulumi.getter(name="certificateUrl")
    def certificate_url(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "certificate_url")

    @property
    @pulumi.getter(name="spBaseUrl")
    def sp_base_url(self) -> str:
        return pulumi.get(self, "sp_base_url")

    @property
    @pulumi.getter(name="spEntityId")
    def sp_entity_id(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "sp_entity_id")

    @property
    @pulumi.getter(name="spMetadataUrl")
    def sp_metadata_url(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "sp_metadata_url")

    @property
    @pulumi.getter(name="spPostUrl")
    def sp_post_url(self) -> str:
        """
        (string)
        """
        return pulumi.get(self, "sp_post_url")


