// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Use the **zpa_saml_attribute** data source to get information about a SAML Attributes from an Identity Provider (IdP). This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Isolation Policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const emailUserSso = zpa.idpController.getSAMLAttribute({
 *     name: "Email_User SSO",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const department = zpa.idpController.getSAMLAttribute({
 *     name: "DepartmentName_IdP_Name_Users",
 * });
 * ```
 */
export function getSAMLAttribute(args?: GetSAMLAttributeArgs, opts?: pulumi.InvokeOptions): Promise<GetSAMLAttributeResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:idpController/getSAMLAttribute:getSAMLAttribute", {
        "id": args.id,
        "idpName": args.idpName,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSAMLAttribute.
 */
export interface GetSAMLAttributeArgs {
    /**
     * The ID of the machine group to be exported.
     */
    id?: string;
    /**
     * The name of the IdP corresponding to the SAML attribute.
     */
    idpName?: string;
    /**
     * The name of the saml attribute to be exported.
     */
    name?: string;
}

/**
 * A collection of values returned by getSAMLAttribute.
 */
export interface GetSAMLAttributeResult {
    /**
     * (string)
     */
    readonly creationTime: string;
    readonly id: string;
    /**
     * (string) The ID of the IdP corresponding to the SAML attribute.
     */
    readonly idpId: string;
    readonly idpName?: string;
    /**
     * (string)
     */
    readonly modifiedTime: string;
    readonly modifiedby: string;
    /**
     * (string)
     */
    readonly name: string;
    /**
     * (string)
     */
    readonly samlName: string;
    /**
     * (string)
     */
    readonly userAttribute: boolean;
}
/**
 * Use the **zpa_saml_attribute** data source to get information about a SAML Attributes from an Identity Provider (IdP). This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Isolation Policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const emailUserSso = zpa.idpController.getSAMLAttribute({
 *     name: "Email_User SSO",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const department = zpa.idpController.getSAMLAttribute({
 *     name: "DepartmentName_IdP_Name_Users",
 * });
 * ```
 */
export function getSAMLAttributeOutput(args?: GetSAMLAttributeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSAMLAttributeResult> {
    return pulumi.output(args).apply((a: any) => getSAMLAttribute(a, opts))
}

/**
 * A collection of arguments for invoking getSAMLAttribute.
 */
export interface GetSAMLAttributeOutputArgs {
    /**
     * The ID of the machine group to be exported.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the IdP corresponding to the SAML attribute.
     */
    idpName?: pulumi.Input<string>;
    /**
     * The name of the saml attribute to be exported.
     */
    name?: pulumi.Input<string>;
}
