// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa
{
    public static class GetZPALSSStatusCodes
    {
        /// <summary>
        /// Use the **zpa_lss_config_status_codes** data source to get information about all LSS status codes in the Zscaler Private Access cloud. This data source is required when the `filter` parameter in the LSS Config Controller resource is set. To learn more see the [Getting Details of All LSS Status Codes](https://help.zscaler.com/zpa/log-streaming-service-configuration-use-cases#GettingLSSStatusCodes)
        /// 
        /// &gt; **NOTE** By Default the ZPA provider will return all status codes
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Zpa = Pulumi.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @this = Zpa.GetZPALSSStatusCodes.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetZPALSSStatusCodesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetZPALSSStatusCodesResult>("zpa:index/getZPALSSStatusCodes:getZPALSSStatusCodes", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetZPALSSStatusCodesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> ZpnAstAuthLog;
        public readonly ImmutableDictionary<string, string> ZpnAuthLog;
        public readonly ImmutableDictionary<string, string> ZpnSysAuthLog;
        public readonly ImmutableDictionary<string, string> ZpnTransLog;

        [OutputConstructor]
        private GetZPALSSStatusCodesResult(
            string id,

            ImmutableDictionary<string, string> zpnAstAuthLog,

            ImmutableDictionary<string, string> zpnAuthLog,

            ImmutableDictionary<string, string> zpnSysAuthLog,

            ImmutableDictionary<string, string> zpnTransLog)
        {
            Id = id;
            ZpnAstAuthLog = zpnAstAuthLog;
            ZpnAuthLog = zpnAuthLog;
            ZpnSysAuthLog = zpnSysAuthLog;
            ZpnTransLog = zpnTransLog;
        }
    }
}
