// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa
{
    public static class GetZPAMachineGroup
    {
        /// <summary>
        /// Use the **zpa_machine_group** data source to get information about a machine group created in the Zscaler Private Access cloud. This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Isolation Policy.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Zpa = Pulumi.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Zpa.GetZPAMachineGroup.Invoke(new()
        ///     {
        ///         Name = "MGR01",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Zpa = Pulumi.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Zpa.GetZPAMachineGroup.Invoke(new()
        ///     {
        ///         Id = "1234567890",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetZPAMachineGroupResult> InvokeAsync(GetZPAMachineGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetZPAMachineGroupResult>("zpa:index/getZPAMachineGroup:getZPAMachineGroup", args ?? new GetZPAMachineGroupArgs(), options.WithDefaults());

        /// <summary>
        /// Use the **zpa_machine_group** data source to get information about a machine group created in the Zscaler Private Access cloud. This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Isolation Policy.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Zpa = Pulumi.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Zpa.GetZPAMachineGroup.Invoke(new()
        ///     {
        ///         Name = "MGR01",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Zpa = Pulumi.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Zpa.GetZPAMachineGroup.Invoke(new()
        ///     {
        ///         Id = "1234567890",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetZPAMachineGroupResult> Invoke(GetZPAMachineGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetZPAMachineGroupResult>("zpa:index/getZPAMachineGroup:getZPAMachineGroup", args ?? new GetZPAMachineGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPAMachineGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the machine group to be exported.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The name of the machine group to be exported.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetZPAMachineGroupArgs()
        {
        }
        public static new GetZPAMachineGroupArgs Empty => new GetZPAMachineGroupArgs();
    }

    public sealed class GetZPAMachineGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the machine group to be exported.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The name of the machine group to be exported.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetZPAMachineGroupInvokeArgs()
        {
        }
        public static new GetZPAMachineGroupInvokeArgs Empty => new GetZPAMachineGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetZPAMachineGroupResult
    {
        /// <summary>
        /// (string)
        /// </summary>
        public readonly string CreationTime;
        /// <summary>
        /// (string)
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// (bool)
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// (string)
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// (string)
        /// </summary>
        public readonly ImmutableArray<Outputs.GetZPAMachineGroupMachineResult> Machines;
        /// <summary>
        /// (string)
        /// </summary>
        public readonly string ModifiedBy;
        /// <summary>
        /// (string)
        /// </summary>
        public readonly string ModifiedTime;
        /// <summary>
        /// (string)
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private GetZPAMachineGroupResult(
            string creationTime,

            string description,

            bool enabled,

            string? id,

            ImmutableArray<Outputs.GetZPAMachineGroupMachineResult> machines,

            string modifiedBy,

            string modifiedTime,

            string? name)
        {
            CreationTime = creationTime;
            Description = description;
            Enabled = enabled;
            Id = id;
            Machines = machines;
            ModifiedBy = modifiedBy;
            ModifiedTime = modifiedTime;
            Name = name;
        }
    }
}
