// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.LSSConfig.Outputs
{

    [OutputType]
    public sealed class LSSConfigControllerConnectorGroup
    {
        /// <summary>
        /// App Connector Group ID(s) where logs will be forwarded to.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private LSSConfigControllerConnectorGroup(ImmutableArray<string> ids)
        {
            Ids = ids;
        }
    }
}
