// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { PolicyAccessTimeOutRuleArgs, PolicyAccessTimeOutRuleState } from "./policyAccessTimeOutRule";
export type PolicyAccessTimeOutRule = import("./policyAccessTimeOutRule").PolicyAccessTimeOutRule;
export const PolicyAccessTimeOutRule: typeof import("./policyAccessTimeOutRule").PolicyAccessTimeOutRule = null as any;
utilities.lazyLoad(exports, ["PolicyAccessTimeOutRule"], () => require("./policyAccessTimeOutRule"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "zpa:TimeoutPolicy/policyAccessTimeOutRule:PolicyAccessTimeOutRule":
                return new PolicyAccessTimeOutRule(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("zpa", "TimeoutPolicy/policyAccessTimeOutRule", _module)
