// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.Outputs
{

    [OutputType]
    public sealed class ZPAApplicationSegmentInspectionCommonAppsDto
    {
        public readonly ImmutableArray<Outputs.ZPAApplicationSegmentInspectionCommonAppsDtoAppsConfig> AppsConfigs;

        [OutputConstructor]
        private ZPAApplicationSegmentInspectionCommonAppsDto(ImmutableArray<Outputs.ZPAApplicationSegmentInspectionCommonAppsDtoAppsConfig> appsConfigs)
        {
            AppsConfigs = appsConfigs;
        }
    }
}
