// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { GetBaCertificateArgs, GetBaCertificateResult, GetBaCertificateOutputArgs } from "./getBaCertificate";
export const getBaCertificate: typeof import("./getBaCertificate").getBaCertificate = null as any;
export const getBaCertificateOutput: typeof import("./getBaCertificate").getBaCertificateOutput = null as any;
utilities.lazyLoad(exports, ["getBaCertificate","getBaCertificateOutput"], () => require("./getBaCertificate"));

