// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The **zpa_trusted_network** data source to get information about a trusted network created in the Zscaler Private Access Mobile Portal. This data source can then be referenced within the following resources:
 *
 * 1. Access Policy
 * 2. Forwarding Policy
 * 3. Inspection Policy
 * 4. Isolation Policy
 * 5. Service Edge Group.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const example = zpa.getZPATrustedNetwork({
 *     name: "trusted_network_name",
 * });
 * ```
 *
 * > **NOTE** To query trusted network that are associated with a specific Zscaler cloud, it is required to append the cloud name to the name of the trusted network as the below example:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const example1 = zpa.getZPATrustedNetwork({
 *     name: "Corporate-Network (zscalertwo.net)",
 * });
 * export const zpaTrustedNetwork = example1.then(example1 => example1.networkId);
 * ```
 */
export function getZPATrustedNetwork(args?: GetZPATrustedNetworkArgs, opts?: pulumi.InvokeOptions): Promise<GetZPATrustedNetworkResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:index/getZPATrustedNetwork:getZPATrustedNetwork", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPATrustedNetwork.
 */
export interface GetZPATrustedNetworkArgs {
    /**
     * The ID of the posture profile to be exported.
     */
    id?: string;
    /**
     * The name of the posture profile to be exported.
     */
    name?: string;
}

/**
 * A collection of values returned by getZPATrustedNetwork.
 */
export interface GetZPATrustedNetworkResult {
    /**
     * (string)
     */
    readonly creationTime: string;
    /**
     * (string)
     */
    readonly domain: string;
    readonly id?: string;
    /**
     * (string)
     */
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name?: string;
    /**
     * (string)
     */
    readonly networkId: string;
    /**
     * (string)
     */
    readonly zscalerCloud: string;
}
/**
 * The **zpa_trusted_network** data source to get information about a trusted network created in the Zscaler Private Access Mobile Portal. This data source can then be referenced within the following resources:
 *
 * 1. Access Policy
 * 2. Forwarding Policy
 * 3. Inspection Policy
 * 4. Isolation Policy
 * 5. Service Edge Group.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const example = zpa.getZPATrustedNetwork({
 *     name: "trusted_network_name",
 * });
 * ```
 *
 * > **NOTE** To query trusted network that are associated with a specific Zscaler cloud, it is required to append the cloud name to the name of the trusted network as the below example:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const example1 = zpa.getZPATrustedNetwork({
 *     name: "Corporate-Network (zscalertwo.net)",
 * });
 * export const zpaTrustedNetwork = example1.then(example1 => example1.networkId);
 * ```
 */
export function getZPATrustedNetworkOutput(args?: GetZPATrustedNetworkOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPATrustedNetworkResult> {
    return pulumi.output(args).apply((a: any) => getZPATrustedNetwork(a, opts))
}

/**
 * A collection of arguments for invoking getZPATrustedNetwork.
 */
export interface GetZPATrustedNetworkOutputArgs {
    /**
     * The ID of the posture profile to be exported.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the posture profile to be exported.
     */
    name?: pulumi.Input<string>;
}
