// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use the **zpa_saml_attribute** data source to get information about a SAML Attributes from an Identity Provider (IdP). This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Isolation Policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const emailUserSso = zpa.getZPASAMLAttribute({
 *     name: "Email_User SSO",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const department = zpa.getZPASAMLAttribute({
 *     name: "DepartmentName_IdP_Name_Users",
 * });
 * ```
 */
export function getZPASAMLAttribute(args?: GetZPASAMLAttributeArgs, opts?: pulumi.InvokeOptions): Promise<GetZPASAMLAttributeResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:index/getZPASAMLAttribute:getZPASAMLAttribute", {
        "id": args.id,
        "idpName": args.idpName,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPASAMLAttribute.
 */
export interface GetZPASAMLAttributeArgs {
    /**
     * The ID of the machine group to be exported.
     */
    id?: string;
    /**
     * The name of the IdP corresponding to the SAML attribute.
     */
    idpName?: string;
    /**
     * The name of the saml attribute to be exported.
     */
    name?: string;
}

/**
 * A collection of values returned by getZPASAMLAttribute.
 */
export interface GetZPASAMLAttributeResult {
    /**
     * (string)
     */
    readonly creationTime: string;
    readonly id: string;
    /**
     * (string) The ID of the IdP corresponding to the SAML attribute.
     */
    readonly idpId: string;
    readonly idpName?: string;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    /**
     * (string)
     * * `modifiedBy` (string)
     * * `modifiedTime` (string)
     */
    readonly name: string;
    /**
     * (string)
     */
    readonly samlName: string;
    /**
     * (string)
     */
    readonly userAttribute: boolean;
}
/**
 * Use the **zpa_saml_attribute** data source to get information about a SAML Attributes from an Identity Provider (IdP). This data source can then be referenced in an Access Policy, Timeout policy, Forwarding Policy, Inspection Policy or Isolation Policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const emailUserSso = zpa.getZPASAMLAttribute({
 *     name: "Email_User SSO",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const department = zpa.getZPASAMLAttribute({
 *     name: "DepartmentName_IdP_Name_Users",
 * });
 * ```
 */
export function getZPASAMLAttributeOutput(args?: GetZPASAMLAttributeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPASAMLAttributeResult> {
    return pulumi.output(args).apply((a: any) => getZPASAMLAttribute(a, opts))
}

/**
 * A collection of arguments for invoking getZPASAMLAttribute.
 */
export interface GetZPASAMLAttributeOutputArgs {
    /**
     * The ID of the machine group to be exported.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the IdP corresponding to the SAML attribute.
     */
    idpName?: pulumi.Input<string>;
    /**
     * The name of the saml attribute to be exported.
     */
    name?: pulumi.Input<string>;
}
